apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-09T02:35:29Z"
  labels:
    app: go
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-07-09T02:35:29Z"
  name: go-stock-app
  namespace: default
  resourceVersion: "27632"
  selfLink: /api/v1/namespaces/default/services/go-stock-app
  uid: a4dc142f-f89c-4e1e-8916-cabd2cb09ae2
spec:
  clusterIP: 10.109.197.246
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
